language: r

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb http://neurodeb.pirsquared.org trusty main'
    packages:
    - libnlopt-dev

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

env:
  global:
    - GIT_AUTHOR_NAME: "Altaf Ali"
    - GIT_AUTHOR_EMAIL: "altaf@fastmail.com"
    - secure: "NBG6e/YMh5yfWHgfrepn3vbqMs+eKkvKma7VMXkR6KUy3CIpj6CWn6pXA8a4uHh3B+yVFEasn42B+cN40olJdedfHx8HL4fxMyFsrzOPwNfV9lEK6DYC2r2+ivl/JKXbZQ+ko0adIje4KbQdw4SWO7B3pAfyA6erbwwD9onGO9F1dAZ7AoN8uroxkvXgkPuUxFDfbf+Fip3TocmY2AbfSA0dYXpcI4xuSPFfRllrl0zs4KjtA/BBpr7qMM0Nq6un6K2dVdRDe9rWUw+DiYY9qUP2dW9N2WKTAi9WYnPgGWq7535dPCoGLKlDrJzj9I22hzzWgyohlO3v2KpOrS9ufTi6RDUng+12MbfD1CmUcOKnObXiMyMCOel3gtNLEqhiG20WZoktDgFYIO6mrduiJ/DMeSMBuNvFjH2PrKwLEj24MzxJkq4pt30/2ZNGM71NXXXLP2XktGx+aTaBvxLij4lY9TbHp6JzgCywg2tEm9zLqve6QHShjPAG8eEdNr2Qk2DOiJb5j05R1DQXmLiGzmNDnl/mzNQt/D9qxBEG8XNj/cnYsDv3LqSB0oUR/8Dr2+euHjyekafVTHm+8pWEuQNdb+fuu265knhnoZZPt6F+G6rahZjM/9AKHOKAerKcA/u8/W7VfQc+Wt4cPyWKzRzBMSejW6wU01mq5eVIp8Y="

#before_install:
#  - wget https://mirrors.netix.net/sourceforge/d/da/daetools/gnu-linux-libs/nlopt-2.4.2.tar.gz
#  - tar xvf nlopt-2.4.2.tar.gz
#  - cd nlopt-2.4.2 && ./configure && make && make test

before_script:
  - chmod +x ./bin/_build.sh
  - chmod +x ./bin/_deploy.sh

script:
  - ./bin/_build.sh
  - ./bin/_deploy.sh

